name: linting-pipeline
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Create package.json
        run: npm init -y
      - name: Install Stylelint
        run: npm install --save-dev stylelint
      - name: Fix Permissions
        run: chmod +x ./node_modules/.bin/stylelint
      - name: Run Stylelint
        run: npx stylelint "**/*.css"
